services:
  # laravel application service
  laravel:
    container_name: laravel-app
    image: laravel-app:1
    build:
      context: .
      dockerfile: docker/be/Dockerfile
    ports:
      - "8000:80"
    command: ["sh","entrypoint.sh"]
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - database-service
  
  # Database service
  database-service:
    image: mysql:8.4.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - database-volume:/var/lib/mysql

volumes:
  database-volume:

networks:
  laravel_network:
    driver: bridge